on: push
name:  Sample Flutter analyze and flutter test check

jobs:
    build:
      name: Dev Pr Checker
      runs-on: ubuntu-latest
      steps:
       
        - uses: actions/checkout@v4
        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
            flutter-version: '3.19.6'
        - run: flutter --version
        - name: Setup Dart SDK
          uses: dart-lang/setup-dart@v1.5.1
          with:
            sdk: 3.3.4
        - run: dart --version
        - run: flutter clean
        - run: flutter pub get
        - run: flutter analyze .
        # - run: flutter test --coverage